[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>", "Jan Macku <jamacku@redhat.com"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
image = "0.21.1"
num-complex = "0.2.1"
rand = "0.8.4"
